export default // 20210820104942
// https://api.github.com/users/cassidoo/followers

[
  {
    "login": "sco",
    "id": 306,
    "node_id": "MDQ6VXNlcjMwNg==",
    "avatar_url": "https://avatars.githubusercontent.com/u/306?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sco",
    "html_url": "https://github.com/sco",
    "followers_url": "https://api.github.com/users/sco/followers",
    "following_url": "https://api.github.com/users/sco/following{/other_user}",
    "gists_url": "https://api.github.com/users/sco/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sco/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sco/subscriptions",
    "organizations_url": "https://api.github.com/users/sco/orgs",
    "repos_url": "https://api.github.com/users/sco/repos",
    "events_url": "https://api.github.com/users/sco/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sco/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "cheeaun",
    "id": 2296,
    "node_id": "MDQ6VXNlcjIyOTY=",
    "avatar_url": "https://avatars.githubusercontent.com/u/2296?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/cheeaun",
    "html_url": "https://github.com/cheeaun",
    "followers_url": "https://api.github.com/users/cheeaun/followers",
    "following_url": "https://api.github.com/users/cheeaun/following{/other_user}",
    "gists_url": "https://api.github.com/users/cheeaun/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/cheeaun/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/cheeaun/subscriptions",
    "organizations_url": "https://api.github.com/users/cheeaun/orgs",
    "repos_url": "https://api.github.com/users/cheeaun/repos",
    "events_url": "https://api.github.com/users/cheeaun/events{/privacy}",
    "received_events_url": "https://api.github.com/users/cheeaun/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "pedrosanta",
    "id": 2737,
    "node_id": "MDQ6VXNlcjI3Mzc=",
    "avatar_url": "https://avatars.githubusercontent.com/u/2737?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/pedrosanta",
    "html_url": "https://github.com/pedrosanta",
    "followers_url": "https://api.github.com/users/pedrosanta/followers",
    "following_url": "https://api.github.com/users/pedrosanta/following{/other_user}",
    "gists_url": "https://api.github.com/users/pedrosanta/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/pedrosanta/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/pedrosanta/subscriptions",
    "organizations_url": "https://api.github.com/users/pedrosanta/orgs",
    "repos_url": "https://api.github.com/users/pedrosanta/repos",
    "events_url": "https://api.github.com/users/pedrosanta/events{/privacy}",
    "received_events_url": "https://api.github.com/users/pedrosanta/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "jeffrafter",
    "id": 4064,
    "node_id": "MDQ6VXNlcjQwNjQ=",
    "avatar_url": "https://avatars.githubusercontent.com/u/4064?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jeffrafter",
    "html_url": "https://github.com/jeffrafter",
    "followers_url": "https://api.github.com/users/jeffrafter/followers",
    "following_url": "https://api.github.com/users/jeffrafter/following{/other_user}",
    "gists_url": "https://api.github.com/users/jeffrafter/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jeffrafter/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jeffrafter/subscriptions",
    "organizations_url": "https://api.github.com/users/jeffrafter/orgs",
    "repos_url": "https://api.github.com/users/jeffrafter/repos",
    "events_url": "https://api.github.com/users/jeffrafter/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jeffrafter/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "benatkin",
    "id": 4126,
    "node_id": "MDQ6VXNlcjQxMjY=",
    "avatar_url": "https://avatars.githubusercontent.com/u/4126?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/benatkin",
    "html_url": "https://github.com/benatkin",
    "followers_url": "https://api.github.com/users/benatkin/followers",
    "following_url": "https://api.github.com/users/benatkin/following{/other_user}",
    "gists_url": "https://api.github.com/users/benatkin/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/benatkin/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/benatkin/subscriptions",
    "organizations_url": "https://api.github.com/users/benatkin/orgs",
    "repos_url": "https://api.github.com/users/benatkin/repos",
    "events_url": "https://api.github.com/users/benatkin/events{/privacy}",
    "received_events_url": "https://api.github.com/users/benatkin/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "jthomp",
    "id": 4753,
    "node_id": "MDQ6VXNlcjQ3NTM=",
    "avatar_url": "https://avatars.githubusercontent.com/u/4753?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jthomp",
    "html_url": "https://github.com/jthomp",
    "followers_url": "https://api.github.com/users/jthomp/followers",
    "following_url": "https://api.github.com/users/jthomp/following{/other_user}",
    "gists_url": "https://api.github.com/users/jthomp/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jthomp/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jthomp/subscriptions",
    "organizations_url": "https://api.github.com/users/jthomp/orgs",
    "repos_url": "https://api.github.com/users/jthomp/repos",
    "events_url": "https://api.github.com/users/jthomp/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jthomp/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "mayoral",
    "id": 5371,
    "node_id": "MDQ6VXNlcjUzNzE=",
    "avatar_url": "https://avatars.githubusercontent.com/u/5371?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mayoral",
    "html_url": "https://github.com/mayoral",
    "followers_url": "https://api.github.com/users/mayoral/followers",
    "following_url": "https://api.github.com/users/mayoral/following{/other_user}",
    "gists_url": "https://api.github.com/users/mayoral/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mayoral/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mayoral/subscriptions",
    "organizations_url": "https://api.github.com/users/mayoral/orgs",
    "repos_url": "https://api.github.com/users/mayoral/repos",
    "events_url": "https://api.github.com/users/mayoral/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mayoral/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "devraj",
    "id": 5961,
    "node_id": "MDQ6VXNlcjU5NjE=",
    "avatar_url": "https://avatars.githubusercontent.com/u/5961?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/devraj",
    "html_url": "https://github.com/devraj",
    "followers_url": "https://api.github.com/users/devraj/followers",
    "following_url": "https://api.github.com/users/devraj/following{/other_user}",
    "gists_url": "https://api.github.com/users/devraj/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/devraj/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/devraj/subscriptions",
    "organizations_url": "https://api.github.com/users/devraj/orgs",
    "repos_url": "https://api.github.com/users/devraj/repos",
    "events_url": "https://api.github.com/users/devraj/events{/privacy}",
    "received_events_url": "https://api.github.com/users/devraj/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "cbetta",
    "id": 7718,
    "node_id": "MDQ6VXNlcjc3MTg=",
    "avatar_url": "https://avatars.githubusercontent.com/u/7718?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/cbetta",
    "html_url": "https://github.com/cbetta",
    "followers_url": "https://api.github.com/users/cbetta/followers",
    "following_url": "https://api.github.com/users/cbetta/following{/other_user}",
    "gists_url": "https://api.github.com/users/cbetta/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/cbetta/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/cbetta/subscriptions",
    "organizations_url": "https://api.github.com/users/cbetta/orgs",
    "repos_url": "https://api.github.com/users/cbetta/repos",
    "events_url": "https://api.github.com/users/cbetta/events{/privacy}",
    "received_events_url": "https://api.github.com/users/cbetta/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "lodestone",
    "id": 8401,
    "node_id": "MDQ6VXNlcjg0MDE=",
    "avatar_url": "https://avatars.githubusercontent.com/u/8401?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/lodestone",
    "html_url": "https://github.com/lodestone",
    "followers_url": "https://api.github.com/users/lodestone/followers",
    "following_url": "https://api.github.com/users/lodestone/following{/other_user}",
    "gists_url": "https://api.github.com/users/lodestone/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/lodestone/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/lodestone/subscriptions",
    "organizations_url": "https://api.github.com/users/lodestone/orgs",
    "repos_url": "https://api.github.com/users/lodestone/repos",
    "events_url": "https://api.github.com/users/lodestone/events{/privacy}",
    "received_events_url": "https://api.github.com/users/lodestone/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "kylecordes",
    "id": 8799,
    "node_id": "MDQ6VXNlcjg3OTk=",
    "avatar_url": "https://avatars.githubusercontent.com/u/8799?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kylecordes",
    "html_url": "https://github.com/kylecordes",
    "followers_url": "https://api.github.com/users/kylecordes/followers",
    "following_url": "https://api.github.com/users/kylecordes/following{/other_user}",
    "gists_url": "https://api.github.com/users/kylecordes/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kylecordes/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kylecordes/subscriptions",
    "organizations_url": "https://api.github.com/users/kylecordes/orgs",
    "repos_url": "https://api.github.com/users/kylecordes/repos",
    "events_url": "https://api.github.com/users/kylecordes/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kylecordes/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "hamiljs",
    "id": 8966,
    "node_id": "MDQ6VXNlcjg5NjY=",
    "avatar_url": "https://avatars.githubusercontent.com/u/8966?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/hamiljs",
    "html_url": "https://github.com/hamiljs",
    "followers_url": "https://api.github.com/users/hamiljs/followers",
    "following_url": "https://api.github.com/users/hamiljs/following{/other_user}",
    "gists_url": "https://api.github.com/users/hamiljs/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/hamiljs/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/hamiljs/subscriptions",
    "organizations_url": "https://api.github.com/users/hamiljs/orgs",
    "repos_url": "https://api.github.com/users/hamiljs/repos",
    "events_url": "https://api.github.com/users/hamiljs/events{/privacy}",
    "received_events_url": "https://api.github.com/users/hamiljs/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "sjelfull",
    "id": 10508,
    "node_id": "MDQ6VXNlcjEwNTA4",
    "avatar_url": "https://avatars.githubusercontent.com/u/10508?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sjelfull",
    "html_url": "https://github.com/sjelfull",
    "followers_url": "https://api.github.com/users/sjelfull/followers",
    "following_url": "https://api.github.com/users/sjelfull/following{/other_user}",
    "gists_url": "https://api.github.com/users/sjelfull/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sjelfull/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sjelfull/subscriptions",
    "organizations_url": "https://api.github.com/users/sjelfull/orgs",
    "repos_url": "https://api.github.com/users/sjelfull/repos",
    "events_url": "https://api.github.com/users/sjelfull/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sjelfull/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "clindsey",
    "id": 11408,
    "node_id": "MDQ6VXNlcjExNDA4",
    "avatar_url": "https://avatars.githubusercontent.com/u/11408?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/clindsey",
    "html_url": "https://github.com/clindsey",
    "followers_url": "https://api.github.com/users/clindsey/followers",
    "following_url": "https://api.github.com/users/clindsey/following{/other_user}",
    "gists_url": "https://api.github.com/users/clindsey/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/clindsey/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/clindsey/subscriptions",
    "organizations_url": "https://api.github.com/users/clindsey/orgs",
    "repos_url": "https://api.github.com/users/clindsey/repos",
    "events_url": "https://api.github.com/users/clindsey/events{/privacy}",
    "received_events_url": "https://api.github.com/users/clindsey/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "tjboudreaux",
    "id": 11684,
    "node_id": "MDQ6VXNlcjExNjg0",
    "avatar_url": "https://avatars.githubusercontent.com/u/11684?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tjboudreaux",
    "html_url": "https://github.com/tjboudreaux",
    "followers_url": "https://api.github.com/users/tjboudreaux/followers",
    "following_url": "https://api.github.com/users/tjboudreaux/following{/other_user}",
    "gists_url": "https://api.github.com/users/tjboudreaux/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tjboudreaux/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tjboudreaux/subscriptions",
    "organizations_url": "https://api.github.com/users/tjboudreaux/orgs",
    "repos_url": "https://api.github.com/users/tjboudreaux/repos",
    "events_url": "https://api.github.com/users/tjboudreaux/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tjboudreaux/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "rauchg",
    "id": 13041,
    "node_id": "MDQ6VXNlcjEzMDQx",
    "avatar_url": "https://avatars.githubusercontent.com/u/13041?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rauchg",
    "html_url": "https://github.com/rauchg",
    "followers_url": "https://api.github.com/users/rauchg/followers",
    "following_url": "https://api.github.com/users/rauchg/following{/other_user}",
    "gists_url": "https://api.github.com/users/rauchg/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rauchg/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rauchg/subscriptions",
    "organizations_url": "https://api.github.com/users/rauchg/orgs",
    "repos_url": "https://api.github.com/users/rauchg/repos",
    "events_url": "https://api.github.com/users/rauchg/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rauchg/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "zazk",
    "id": 13297,
    "node_id": "MDQ6VXNlcjEzMjk3",
    "avatar_url": "https://avatars.githubusercontent.com/u/13297?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/zazk",
    "html_url": "https://github.com/zazk",
    "followers_url": "https://api.github.com/users/zazk/followers",
    "following_url": "https://api.github.com/users/zazk/following{/other_user}",
    "gists_url": "https://api.github.com/users/zazk/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/zazk/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/zazk/subscriptions",
    "organizations_url": "https://api.github.com/users/zazk/orgs",
    "repos_url": "https://api.github.com/users/zazk/repos",
    "events_url": "https://api.github.com/users/zazk/events{/privacy}",
    "received_events_url": "https://api.github.com/users/zazk/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "dturton",
    "id": 15795,
    "node_id": "MDQ6VXNlcjE1Nzk1",
    "avatar_url": "https://avatars.githubusercontent.com/u/15795?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dturton",
    "html_url": "https://github.com/dturton",
    "followers_url": "https://api.github.com/users/dturton/followers",
    "following_url": "https://api.github.com/users/dturton/following{/other_user}",
    "gists_url": "https://api.github.com/users/dturton/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dturton/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dturton/subscriptions",
    "organizations_url": "https://api.github.com/users/dturton/orgs",
    "repos_url": "https://api.github.com/users/dturton/repos",
    "events_url": "https://api.github.com/users/dturton/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dturton/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "p3k",
    "id": 16631,
    "node_id": "MDQ6VXNlcjE2NjMx",
    "avatar_url": "https://avatars.githubusercontent.com/u/16631?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/p3k",
    "html_url": "https://github.com/p3k",
    "followers_url": "https://api.github.com/users/p3k/followers",
    "following_url": "https://api.github.com/users/p3k/following{/other_user}",
    "gists_url": "https://api.github.com/users/p3k/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/p3k/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/p3k/subscriptions",
    "organizations_url": "https://api.github.com/users/p3k/orgs",
    "repos_url": "https://api.github.com/users/p3k/repos",
    "events_url": "https://api.github.com/users/p3k/events{/privacy}",
    "received_events_url": "https://api.github.com/users/p3k/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "timdorr",
    "id": 17882,
    "node_id": "MDQ6VXNlcjE3ODgy",
    "avatar_url": "https://avatars.githubusercontent.com/u/17882?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/timdorr",
    "html_url": "https://github.com/timdorr",
    "followers_url": "https://api.github.com/users/timdorr/followers",
    "following_url": "https://api.github.com/users/timdorr/following{/other_user}",
    "gists_url": "https://api.github.com/users/timdorr/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/timdorr/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/timdorr/subscriptions",
    "organizations_url": "https://api.github.com/users/timdorr/orgs",
    "repos_url": "https://api.github.com/users/timdorr/repos",
    "events_url": "https://api.github.com/users/timdorr/events{/privacy}",
    "received_events_url": "https://api.github.com/users/timdorr/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "scottlaplant",
    "id": 17899,
    "node_id": "MDQ6VXNlcjE3ODk5",
    "avatar_url": "https://avatars.githubusercontent.com/u/17899?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/scottlaplant",
    "html_url": "https://github.com/scottlaplant",
    "followers_url": "https://api.github.com/users/scottlaplant/followers",
    "following_url": "https://api.github.com/users/scottlaplant/following{/other_user}",
    "gists_url": "https://api.github.com/users/scottlaplant/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/scottlaplant/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/scottlaplant/subscriptions",
    "organizations_url": "https://api.github.com/users/scottlaplant/orgs",
    "repos_url": "https://api.github.com/users/scottlaplant/repos",
    "events_url": "https://api.github.com/users/scottlaplant/events{/privacy}",
    "received_events_url": "https://api.github.com/users/scottlaplant/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "ian",
    "id": 19853,
    "node_id": "MDQ6VXNlcjE5ODUz",
    "avatar_url": "https://avatars.githubusercontent.com/u/19853?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ian",
    "html_url": "https://github.com/ian",
    "followers_url": "https://api.github.com/users/ian/followers",
    "following_url": "https://api.github.com/users/ian/following{/other_user}",
    "gists_url": "https://api.github.com/users/ian/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ian/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ian/subscriptions",
    "organizations_url": "https://api.github.com/users/ian/orgs",
    "repos_url": "https://api.github.com/users/ian/repos",
    "events_url": "https://api.github.com/users/ian/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ian/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "matmar10",
    "id": 19975,
    "node_id": "MDQ6VXNlcjE5OTc1",
    "avatar_url": "https://avatars.githubusercontent.com/u/19975?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/matmar10",
    "html_url": "https://github.com/matmar10",
    "followers_url": "https://api.github.com/users/matmar10/followers",
    "following_url": "https://api.github.com/users/matmar10/following{/other_user}",
    "gists_url": "https://api.github.com/users/matmar10/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/matmar10/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/matmar10/subscriptions",
    "organizations_url": "https://api.github.com/users/matmar10/orgs",
    "repos_url": "https://api.github.com/users/matmar10/repos",
    "events_url": "https://api.github.com/users/matmar10/events{/privacy}",
    "received_events_url": "https://api.github.com/users/matmar10/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "matiasinsaurralde",
    "id": 20110,
    "node_id": "MDQ6VXNlcjIwMTEw",
    "avatar_url": "https://avatars.githubusercontent.com/u/20110?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/matiasinsaurralde",
    "html_url": "https://github.com/matiasinsaurralde",
    "followers_url": "https://api.github.com/users/matiasinsaurralde/followers",
    "following_url": "https://api.github.com/users/matiasinsaurralde/following{/other_user}",
    "gists_url": "https://api.github.com/users/matiasinsaurralde/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/matiasinsaurralde/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/matiasinsaurralde/subscriptions",
    "organizations_url": "https://api.github.com/users/matiasinsaurralde/orgs",
    "repos_url": "https://api.github.com/users/matiasinsaurralde/repos",
    "events_url": "https://api.github.com/users/matiasinsaurralde/events{/privacy}",
    "received_events_url": "https://api.github.com/users/matiasinsaurralde/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "keithduncan",
    "id": 22101,
    "node_id": "MDQ6VXNlcjIyMTAx",
    "avatar_url": "https://avatars.githubusercontent.com/u/22101?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/keithduncan",
    "html_url": "https://github.com/keithduncan",
    "followers_url": "https://api.github.com/users/keithduncan/followers",
    "following_url": "https://api.github.com/users/keithduncan/following{/other_user}",
    "gists_url": "https://api.github.com/users/keithduncan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/keithduncan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/keithduncan/subscriptions",
    "organizations_url": "https://api.github.com/users/keithduncan/orgs",
    "repos_url": "https://api.github.com/users/keithduncan/repos",
    "events_url": "https://api.github.com/users/keithduncan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/keithduncan/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "robbyoconnor",
    "id": 23088,
    "node_id": "MDQ6VXNlcjIzMDg4",
    "avatar_url": "https://avatars.githubusercontent.com/u/23088?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/robbyoconnor",
    "html_url": "https://github.com/robbyoconnor",
    "followers_url": "https://api.github.com/users/robbyoconnor/followers",
    "following_url": "https://api.github.com/users/robbyoconnor/following{/other_user}",
    "gists_url": "https://api.github.com/users/robbyoconnor/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/robbyoconnor/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/robbyoconnor/subscriptions",
    "organizations_url": "https://api.github.com/users/robbyoconnor/orgs",
    "repos_url": "https://api.github.com/users/robbyoconnor/repos",
    "events_url": "https://api.github.com/users/robbyoconnor/events{/privacy}",
    "received_events_url": "https://api.github.com/users/robbyoconnor/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "MHenderson",
    "id": 23988,
    "node_id": "MDQ6VXNlcjIzOTg4",
    "avatar_url": "https://avatars.githubusercontent.com/u/23988?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/MHenderson",
    "html_url": "https://github.com/MHenderson",
    "followers_url": "https://api.github.com/users/MHenderson/followers",
    "following_url": "https://api.github.com/users/MHenderson/following{/other_user}",
    "gists_url": "https://api.github.com/users/MHenderson/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/MHenderson/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/MHenderson/subscriptions",
    "organizations_url": "https://api.github.com/users/MHenderson/orgs",
    "repos_url": "https://api.github.com/users/MHenderson/repos",
    "events_url": "https://api.github.com/users/MHenderson/events{/privacy}",
    "received_events_url": "https://api.github.com/users/MHenderson/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "jxpx777",
    "id": 24182,
    "node_id": "MDQ6VXNlcjI0MTgy",
    "avatar_url": "https://avatars.githubusercontent.com/u/24182?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jxpx777",
    "html_url": "https://github.com/jxpx777",
    "followers_url": "https://api.github.com/users/jxpx777/followers",
    "following_url": "https://api.github.com/users/jxpx777/following{/other_user}",
    "gists_url": "https://api.github.com/users/jxpx777/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jxpx777/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jxpx777/subscriptions",
    "organizations_url": "https://api.github.com/users/jxpx777/orgs",
    "repos_url": "https://api.github.com/users/jxpx777/repos",
    "events_url": "https://api.github.com/users/jxpx777/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jxpx777/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "danielfilho",
    "id": 24597,
    "node_id": "MDQ6VXNlcjI0NTk3",
    "avatar_url": "https://avatars.githubusercontent.com/u/24597?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/danielfilho",
    "html_url": "https://github.com/danielfilho",
    "followers_url": "https://api.github.com/users/danielfilho/followers",
    "following_url": "https://api.github.com/users/danielfilho/following{/other_user}",
    "gists_url": "https://api.github.com/users/danielfilho/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/danielfilho/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/danielfilho/subscriptions",
    "organizations_url": "https://api.github.com/users/danielfilho/orgs",
    "repos_url": "https://api.github.com/users/danielfilho/repos",
    "events_url": "https://api.github.com/users/danielfilho/events{/privacy}",
    "received_events_url": "https://api.github.com/users/danielfilho/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "tmilewski",
    "id": 26691,
    "node_id": "MDQ6VXNlcjI2Njkx",
    "avatar_url": "https://avatars.githubusercontent.com/u/26691?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tmilewski",
    "html_url": "https://github.com/tmilewski",
    "followers_url": "https://api.github.com/users/tmilewski/followers",
    "following_url": "https://api.github.com/users/tmilewski/following{/other_user}",
    "gists_url": "https://api.github.com/users/tmilewski/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tmilewski/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tmilewski/subscriptions",
    "organizations_url": "https://api.github.com/users/tmilewski/orgs",
    "repos_url": "https://api.github.com/users/tmilewski/repos",
    "events_url": "https://api.github.com/users/tmilewski/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tmilewski/received_events",
    "type": "User",
    "site_admin": false
  }
] 
